import { Download, Pause, Play, Save, X } from 'lucide-react';
import { Character, type ExpressionName, type EyeVariant, type MouthVariant, type EyebrowVariant } from 'faceshape-react';
import type { ViewProps } from '../models/viewProps';
import { translate } from '../models/types';
import { useAvatarPresenter } from '../presenters/useAvatarPresenter';
import { avatarShapes, avatarExpressions, avatarEyes, avatarMouths, avatarEyebrows } from '../models/avatars';
import { ExternalLink } from '../components/Actions';
export function AvatarView({ language, avatarCollection }: ViewProps) {
  const p = useAvatarPresenter(); const t = (en: string, es: string) => translate(language, [en, es]);
  return <div className="pad avatar-lab"><p className="kicker">PLAYGROUND / 01</p><h2 style={{ fontSize: 29 }}>{t('Give it a little character.', 'Dale un poco de personalidad.')}</h2>
    <div className="avatar-layout"><div className="avatar-preview"><div className="avatar-stage"><Character ref={p.svgRef} name={p.name} shape={p.resolvedShape} expression={p.expression} face={{ eyes: p.eyes, mouth: p.mouth, eyebrows: p.eyebrows }} color={p.color} size={180} label={t('Customizable avatar', 'Avatar personalizable')} motion={{ idle: p.animated, blink: p.animated, lookAt: p.animated ? 'cursor' : undefined }} reducedMotion={!p.animated}/></div><button className="btn avatar-animation" aria-pressed={p.animated} onClick={() => p.setAnimated(!p.animated)}>{p.animated ? <Pause size={14}/> : <Play size={14}/>} {p.animated ? t('Pause animation', 'Pausar animación') : t('Animate', 'Animar')}</button>{avatarCollection && <button className="btn orange avatar-save" disabled={avatarCollection.avatars.length >= 5} onClick={() => avatarCollection.save(p.config)}><Save size={14}/>{t('Save to desktop', 'Guardar en escritorio')}</button>}</div>
    <div className="controls">
      <div><label htmlFor="avatar-name">{t('Name', 'Nombre')}</label><input id="avatar-name" type="text" maxLength={80} value={p.name} onChange={e => p.setName(e.target.value)}/></div>
      <div><label htmlFor="avatar-shape-select">{t('Shape', 'Forma')}</label><select id="avatar-shape-select" value={p.shape} onChange={e => p.setShape(e.target.value)}>{Object.entries(avatarShapes).map(([id, option]) => <option key={id} value={id}>{translate(language, option.label)}</option>)}</select></div>
      <div><label htmlFor="avatar-expression">{t('Expression', 'Expresión')}</label><select id="avatar-expression" value={p.expression} onChange={e => p.setExpression(e.target.value as ExpressionName)}>{Object.entries(avatarExpressions).map(([id, label]) => <option key={id} value={id}>{translate(language, label)}</option>)}</select></div>
      <div><label htmlFor="avatar-eyes">{t('Eyes', 'Ojos')}</label><select id="avatar-eyes" value={p.eyes} onChange={e => p.setEyes(e.target.value as EyeVariant)}>{Object.entries(avatarEyes).map(([id, label]) => <option key={id} value={id}>{translate(language, label)}</option>)}</select></div>
      <div><label htmlFor="avatar-mouth">{t('Mouth', 'Boca')}</label><select id="avatar-mouth" value={p.mouth} onChange={e => p.setMouth(e.target.value as MouthVariant)}>{Object.entries(avatarMouths).map(([id, label]) => <option key={id} value={id}>{translate(language, label)}</option>)}</select></div>
      <div><label htmlFor="avatar-eyebrows">{t('Eyebrows', 'Cejas')}</label><select id="avatar-eyebrows" value={p.eyebrows} onChange={e => p.setEyebrows(e.target.value as EyebrowVariant)}>{Object.entries(avatarEyebrows).map(([id, label]) => <option key={id} value={id}>{translate(language, label)}</option>)}</select></div>
      <div className="swatch-container"><label>{t('Color', 'Color')}</label><div className="swatches">{p.colors.map((color, i) => <button key={color} style={{ background: color }} className={p.color === color ? 'selected' : ''} aria-label={`Color ${i + 1}`} aria-pressed={p.color === color} onClick={() => p.setColor(color)}/>)}</div><button className="btn" id="export-avatar" onClick={p.download}>{t('Download SVG', 'Descargar SVG')}<Download size={14}/></button></div>
    </div></div>
    {avatarCollection && <section className="saved-avatars" aria-label={t('Saved avatars', 'Avatares guardados')}><div className="saved-avatars-heading"><h3>{t('Your desktop characters', 'Tus personajes del escritorio')}</h3><span>{avatarCollection.avatars.length}/5</span></div><p className="notice">{t('Saved in this browser. Drag up to five characters around your desktop. Select one to edit it; saving creates a new copy.', 'Se guardan en este navegador. Podés arrastrar hasta cinco personajes por tu escritorio. Elegí uno para editarlo; guardar crea una copia.')}</p>{avatarCollection.error && <p className="avatar-storage-error" role="alert">{t('Your browser could not save this change. Try enabling local storage.', 'El navegador no pudo guardar el cambio. Probá habilitar el almacenamiento local.')}</p>}{avatarCollection.avatars.length >= 5 && <p className="notice" role="status">{t('All five spots are taken. Remove a character to save another.', 'Los cinco lugares están ocupados. Eliminá un personaje para guardar otro.')}</p>}<div className="saved-avatar-list">{avatarCollection.avatars.map(avatar => <div key={avatar.id} className="saved-avatar"><button className="saved-avatar-load" onClick={() => p.load(avatar)}><Character name={avatar.name} shape={avatarShapes[avatar.shape].shape} expression={avatar.expression} face={{ eyes: avatar.eyes, mouth: avatar.mouth, eyebrows: avatar.eyebrows }} color={avatar.color} size={38} reducedMotion/><span>{avatar.name || t('Unnamed', 'Sin nombre')}</span></button><button className="saved-avatar-remove" aria-label={t(`Remove ${avatar.name || 'avatar'}`, `Eliminar ${avatar.name || 'avatar'}`)} onClick={() => avatarCollection.remove(avatar.id)}><X size={14}/></button></div>)}</div></section>}
    <p className="notice">{t('Powered by my faceshape-react library. The name changes the character’s geometry; combine shapes, expressions and facial features to make it yours.', 'Hecho con mi librería faceshape-react. El nombre cambia la geometría del personaje; combiná formas, expresiones y rasgos para hacerlo tuyo.')}</p>
    <ExternalLink href="https://ketzelitvak.github.io/faceshape-react/">{t('Explore the full library', 'Explorar la librería completa')}</ExternalLink>
  </div>;
}
export function ToolsView({ language }: ViewProps) { const t = (en: string, es: string) => translate(language, [en, es]); return <div className="pad"><img className="tools-project-logo" src="./assets/ketze-tools-logo.png" alt="Ketze Tools logo"/><p className="kicker">KETZE TOOLS</p><h2 style={{ fontSize: 29 }}>{t('Small tools for everyday development.', 'Herramientas para el desarrollo diario.')}</h2><p className="description">{t('A collection of developer utilities, including JSON formatting and URL encoding and decoding. Explore the tools on the project website.', 'Una colección de utilidades para desarrolladores, como formatear JSON y codificar o decodificar URLs. Explorá las herramientas en la web del proyecto.')}</p><ExternalLink href="https://ketze.com.ar">{t('Open Ketze Tools', 'Abrir Ketze Tools')}</ExternalLink></div>; }
