import { Mail, ArrowUpRight } from 'lucide-react';
import type { ViewProps } from '../models/viewProps';
import { translate } from '../models/types';
import { ProjectListView } from './ProjectViews';
import { OpenButton } from '../components/Actions';
export function ProfileView({ language }: ViewProps) { const t = (en: string, es: string) => translate(language, [en, es]); const timeline = [
['2022 →', 'Geopagos', t('Senior Full Stack Developer. Contribute to the design and development of Acquirer in a Box. Experience in internal backoffice, React microfrontends, backend services with C#/.NET and Python, payment security and access control.', 'Desarrollador Full Stack Senior. Participo en el diseño y desarrollo de Acquirer in a Box. Experiencia en backoffice, microfrontends React, servicios con C#/.NET y Python, seguridad de pagos y control de acceso.')],
['2021 →', 'UTN FRBA', t('Information Systems Engineering. Expected graduation: December 2026. Teaching assistant in Programming Paradigms since 2023.', 'Ingeniería en Sistemas de Información. Graduación estimada: diciembre 2026. Ayudante de Paradigmas de Programación desde 2023.')],
['2021–2025', t('Youth leadership', 'Liderazgo juvenil'), t('Five years as a youth leader and nonformal educator (Madrich) at Círculo Social Hebreo Argentino.', 'Cinco años como líder juvenil y educador no formal (madrij) en Círculo Social Hebreo Argentino.')]
]; return <div className="pad profile-body"><div className="profile-top"><div className="monogram"><img src="./assets/ketze-logo.png" alt=""/></div><div><h2>Ezequiel Ilan Litvak</h2><small>Senior Full Stack Developer · Buenos Aires</small></div></div><p>{t('I enjoy understanding the entire product and making its parts work together. Collaborative and empathetic, with a positive attitude and a commitment to continuous learning.', 'Me gusta entender el producto completo y hacer que sus partes funcionen juntas. Soy colaborativo y empático, con una actitud positiva y compromiso con el aprendizaje continuo.')}</p><div className="timeline">{timeline.map(([date, title, description]) => <div key={title} className="timeline-row"><span>{date}</span><div><b>{title}</b><small>{description}</small></div></div>)}</div><div className="tags">{['C# / .NET', 'TypeScript', 'React / Next.js', 'Python', 'Node.js', 'AWS'].map(s => <span key={s}>{s}</span>)}</div><a className="btn primary" href="mailto:ketze.contact@gmail.com?subject=CV%20request%20%E2%80%94%20Ketze%20Studio">{t('Request CV', 'Solicitar CV')}<Mail size={14}/></a></div>; }
export function ContactView({ language }: ViewProps) { const t = (en: string, es: string) => translate(language, [en, es]); return <div className="contact-card"><p className="kicker">{t('OPEN A CONVERSATION', 'ABRÍ UNA CONVERSACIÓN')}</p><h2>{t('Let’s build', 'Construyamos')}<br/>{t('something good.', 'algo bueno.')}</h2><p>{t('Want to talk about a project, an opportunity or something you’re building? Here’s where to find me.', '¿Querés conversar sobre un proyecto, una oportunidad o algo que estás construyendo? Podés encontrarme acá.')}</p>{[['mailto:ketze.contact@gmail.com', 'ketze.contact@gmail.com'], ['https://www.linkedin.com/in/ezequiel-litvak-30002822a/', 'LinkedIn'], ['https://github.com/ketzeLitvak', 'GitHub / ketzeLitvak']].map(([href, label]) => <a key={href} className="contact-link" href={href} target={href.startsWith('https') ? '_blank' : undefined} rel="noopener">{label}<ArrowUpRight size={15}/></a>)}</div>; }
export function QuickView({ language, openApp }: ViewProps) { const t = (en: string, es: string) => translate(language, [en, es]); return <div className="pad"><p className="kicker">{t('THE SHORT VERSION', 'LA VERSIÓN CORTA')}</p><h2 style={{ fontSize: 32 }}>Ezequiel Ilan Litvak</h2><p className="description">{t('Senior Full Stack Developer · Nearly five years of experience · Buenos Aires, Argentina', 'Desarrollador Full Stack Senior · Casi cinco años de experiencia · Buenos Aires, Argentina')}</p><div className="quick-section"><h3>Geopagos</h3><p>{t('Contribute to the design and development of Acquirer in a Box. Experience in backoffice, payment security, backend services and React microfrontends.', 'Participo en el diseño y desarrollo de Acquirer in a Box. Experiencia en backoffice, seguridad de pagos, servicios backend y microfrontends React.')}</p></div><div className="quick-section"><h3>{t('Selected projects', 'Proyectos destacados')}</h3><ProjectListView language={language} openApp={openApp}/></div><div className="quick-section"><h3>UTN FRBA</h3><p>{t('Final-year Information Systems Engineering student and teaching assistant. English: professional working proficiency.', 'Estudiante del último año de Ingeniería en Sistemas de Información y ayudante de cátedra. Inglés avanzado para trabajar.')}</p></div><OpenButton id="profile" openApp={openApp} primary>{t('Full profile & CV', 'Perfil completo y CV')}</OpenButton> <OpenButton id="contact" openApp={openApp}>{t('Contact', 'Contacto')}</OpenButton></div>; }
